// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaiwanAgri.Modules.Weather.Data;

#nullable disable

namespace TaiwanAgri.Modules.Weather.Data.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    [Migration("20260418175312_AddtheSourceRecordIdfield")]
    partial class AddtheSourceRecordIdfield
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaiwanAgri.Modules.Weather.Entities.PestAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CitiesRaw")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlantNamesRaw")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("PubDate")
                        .HasColumnType("date");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SourceHash")
                        .IsUnique()
                        .HasDatabaseName("IX_PestAlerts_SourceHash");

                    b.ToTable("PestAlerts", (string)null);
                });

            modelBuilder.Entity("TaiwanAgri.Modules.Weather.Entities.PestAlertCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlertId")
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AlertId");

                    b.HasIndex("CityName")
                        .HasDatabaseName("IX_PestAlertCities_CityName");

                    b.ToTable("PestAlertCities", (string)null);
                });

            modelBuilder.Entity("TaiwanAgri.Modules.Weather.Entities.PestAlertCrop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlertId")
                        .HasColumnType("int");

                    b.Property<string>("CropName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AlertId");

                    b.HasIndex("CropName")
                        .HasDatabaseName("IX_PestAlertCrops_CropName");

                    b.ToTable("PestAlertCrops", (string)null);
                });

            modelBuilder.Entity("TaiwanAgri.Modules.Weather.Entities.PestDecadeSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Average")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("PestName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("ProportionIsland")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TenDays")
                        .HasColumnType("int");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PestName", "Year", "Month", "TenDays", "City", "Town")
                        .IsUnique()
                        .HasDatabaseName("IX_PestDecadeSummaries_Unique");

                    b.ToTable("PestDecadeSummaries", (string)null);
                });

            modelBuilder.Entity("TaiwanAgri.Modules.Weather.Entities.PestRuleConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpiryDays")
                        .HasColumnType("int");

                    b.Property<string>("FilterJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SourceTable")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Threshold")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RuleName")
                        .HasDatabaseName("IX_PestRuleConfigs_RuleName");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("IX_PestRuleConfigs_UserId_IsActive");

                    b.ToTable("PestRuleConfigs", (string)null);
                });

            modelBuilder.Entity("TaiwanAgri.Modules.Weather.Entities.RainfallObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Attribute")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Hour12")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("Hour24")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("Hour3")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("Hour6")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("Min10")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("Now")
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Rain")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StationId", "ObservedAt")
                        .IsUnique()
                        .HasDatabaseName("IX_RainfallObservations_StationId_ObservedAt");

                    b.ToTable("RainfallObservations", (string)null);
                });

            modelBuilder.Entity("TaiwanAgri.Modules.Weather.Entities.RainfallStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Elevation")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TownCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TownName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StationId")
                        .IsUnique()
                        .HasDatabaseName("IX_RainfallStations_StationId");

                    b.ToTable("RainfallStations", (string)null);
                });

            modelBuilder.Entity("TaiwanAgri.Modules.Weather.Entities.UserNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PestRuleConfigId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceRecordId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PestRuleConfigId");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("IX_UserNotifications_UserId_IsRead");

                    b.ToTable("UserNotifications", (string)null);
                });

            modelBuilder.Entity("TaiwanAgri.Modules.Weather.Entities.WeatherObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("DailyMaxTemp")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("DailyMinTemp")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("Elevation")
                        .HasColumnType("int");

                    b.Property<decimal?>("Humidity")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal?>("MaxGust")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("MaxGustDirection")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Pressure")
                        .HasColumnType("decimal(7,3)");

                    b.Property<decimal?>("Rainfall24h")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SunshineHours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("TownCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TownName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WindDirection")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("WindSpeed")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("StationId")
                        .HasDatabaseName("IX_WeatherObservations_StationId");

                    b.HasIndex("CityCode", "ObservedAt")
                        .HasDatabaseName("IX_WeatherObservations_CityCode_ObservedAt");

                    b.ToTable("WeatherObservations", (string)null);
                });

            modelBuilder.Entity("TaiwanAgri.Modules.Weather.Entities.PestAlertCity", b =>
                {
                    b.HasOne("TaiwanAgri.Modules.Weather.Entities.PestAlert", "Alert")
                        .WithMany("Cities")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("TaiwanAgri.Modules.Weather.Entities.PestAlertCrop", b =>
                {
                    b.HasOne("TaiwanAgri.Modules.Weather.Entities.PestAlert", "Alert")
                        .WithMany("Crops")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("TaiwanAgri.Modules.Weather.Entities.UserNotification", b =>
                {
                    b.HasOne("TaiwanAgri.Modules.Weather.Entities.PestRuleConfig", "PestRuleConfig")
                        .WithMany()
                        .HasForeignKey("PestRuleConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PestRuleConfig");
                });

            modelBuilder.Entity("TaiwanAgri.Modules.Weather.Entities.PestAlert", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Crops");
                });
#pragma warning restore 612, 618
        }
    }
}
