// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaiwanAgri.Core.Infrastructure.Data;

#nullable disable

namespace TaiwanAgri.Core.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20260515160820_AddNavModuleAndRoleModulePermission")]
    partial class AddNavModuleAndRoleModulePermission
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaiwanAgri.Core.Entities.NavModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("NavModules", "core");
                });

            modelBuilder.Entity("TaiwanAgri.Core.Entities.RoleModulePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<bool>("CanView")
                        .HasColumnType("bit");

                    b.HasKey("RoleId", "ModuleId");

                    b.HasIndex("ModuleId");

                    b.ToTable("RoleModulePermissions", "core");
                });

            modelBuilder.Entity("TaiwanAgri.Core.Infrastructure.Entities.SyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("LastSyncedDate")
                        .HasColumnType("date");

                    b.Property<string>("SyncKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SyncKey")
                        .IsUnique()
                        .HasDatabaseName("IX_SyncStates_SyncKey");

                    b.ToTable("SyncStates", "core");
                });

            modelBuilder.Entity("TaiwanAgri.Core.Entities.NavModule", b =>
                {
                    b.HasOne("TaiwanAgri.Core.Entities.NavModule", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TaiwanAgri.Core.Entities.RoleModulePermission", b =>
                {
                    b.HasOne("TaiwanAgri.Core.Entities.NavModule", "NavModule")
                        .WithMany("RoleModulePermissions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NavModule");
                });

            modelBuilder.Entity("TaiwanAgri.Core.Entities.NavModule", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("RoleModulePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
